### ISSUE TITLE
Rumble Support not working 

### ISSUE THREAD

**Issue by RyanMac84** [DavidPagels/retro-pico-switch#20] opened 2023-09-10 13:14 UTC
Hi, 

I'm using a n64 controller wired, which works in Windows 11 fine using the Initial release, but when I flash the Rumble Support release it still shows in Windows but there is no input.

**Comment by DavidPagels** [comment] 2023-09-10 21:32
Closing as this is a duplicate of #11

**Closed as completed by DavidPagels** 2023-09-10 21:32 UTC
